---
title: "Redlining code for PLOSOne Manuscript (forthcoming)"
authors: "Victoria Fisher & Nicole Alkhouri, Isaacson Michel, Caitlyn O'Connor, Nadia N. Abuelezam"
date: "2024-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


library(pacman)

p_load(tidyverse,
       tidycensus,
       tigris,
       ggplot2,
       gtsummary,
       DescTools,
       datawizard,
       excessmort,
       lubridate,
       readxl,
       haven,
       MASS,
       lme4,
       lmerTest,
       nlme,
       glmmTMB,
       merTools,
       bbmle,
       zctaCrosswalk,
       performance,
       ggpubr,
       foreign,
       DHARMa,
       sf,
       rms,
       mlogit,
       effects,
       splines,
       car,
       Publish,
       msme,
       plm,
       broom,
       forestplot,
       sjPlot,
       sjlabelled,
       sjmisc,
       clusterSim,
       geepack,
       geeM,
       gridExtra,
       fixest,
       foreign,
       DataCombine,
       naniar)


```

#Loading datasets

```{r}

boston_covid_df <- read_csv('boston_zcta_counts_df.csv')

holc_ratings <- read_xlsx("Meier_2023_ICPSR_Historic Redlining Indicator 2020.xlsx")

holc_ratings <- holc_ratings %>% dplyr::select(!6)

ZIP_TRACT_2020 <- read_xlsx("TRACT_ZIP_122020.xlsx")


```



```{r}

#2020 ZIP to 2020 ZCTA xwalk

colnames(ZIP_TRACT_2020)[1:2] <- c("TRACTID20", "ZCTA")

ZIP_TRACT_2020 <- ZIP_TRACT_2020 %>% dplyr::select(c(1:2))

```

```{r}

## 2020 covariates -- will need Census API key to insert between the quotation marks below 

census_api_key("CENSUS API KEY HERE", install = TRUE)
readRenviron("~/.Renviron")

v2020 <- load_variables(2020, "acs5")
covariates <- c(total_pop = "B01003_001",
                med_age = "B01002_001",
                OWN = "B25003_002",
                male_pop = "B01001_002",
                FB = "B05008_001",
                avg_hh = "B25010_001",
                MHMVAL = "B25107_001",
                COL = "B15003_022",
                NHWHT = "B02001_002",
                POP = "B01003_001",
                A75UP = "B17024_119",
                A18UND = "B09001_001",
                ASIAN = "B01001D_001",
                NHBLK = "B01001B_001",
                HISP = "B01001I_001"
              )



years <- 2020:2022 #pulls American Community Survey data from 2019 - 2021
names(years) <- years
demo_vars <- purrr::map_dfr(years, ~{
  get_acs(
    geography = "zcta",
    variables = covariates, 
    year = .x
    )
}, .id = "year")

geometry <- get_acs(geography = "zcta",
                    year = 2020,
                    variables = "B08202_005",
                    geometry = TRUE) %>% shift_geometry()

df_demo <- demo_vars %>%
  pivot_wider(id_cols = c("year", "GEOID"),
              names_from = c("variable"),
              values_from = "estimate")
colnames(df_demo)[2] <- "ZCTA"
colnames(df_demo)[1] <- "YEAR"

colnames(geometry)[1] <- "ZCTA"
geometry <- geometry %>% dplyr::select(c(1, 6))

df_demo <- merge(df_demo, geometry, by = "ZCTA", all = TRUE)

```



#Merging HOLC and tract --> ZIP

```{r}

colnames(holc_ratings)[1] <- "TRACTID"

boston_zip <- as.data.frame(unique(boston_covid_df$ZCTA))

colnames(boston_zip)[1] <- "ZCTA"

boston_tract_zip <- merge(ZIP_TRACT_2020, boston_zip, by = "ZCTA")

boston_holc_tract_zip <- merge(holc_ratings, boston_tract_zip, by.x = "TRACTID", by.y = "TRACTID20")

#Creating map of included  vs excluded ZCTAs
boston_holc_for_map <- boston_tract_zip

boston_holc_for_map$has_holc <- boston_holc_for_map$ZCTA %in% boston_holc_tract_zip$ZCTA

boston_holc_for_map <- merge(boston_holc_for_map, geometry, by = "ZCTA")

boston_holc_for_map <- st_as_sf(boston_holc_for_map)

st_crs(boston_holc_for_map)

st_bbox(boston_holc_for_map)

boston_holc_for_map <- boston_holc_for_map[st_is_valid(boston_holc_for_map), ]

holc_map <- ggplot(data = boston_holc_for_map) +
  geom_sf(aes(fill = has_holc)) + 
  scale_fill_manual(name = "Has HOLC Grade", values = c("#696969", "#D3D3D3")) + 
  theme_void() +
  labs(title = "Boston ZCTAs with Historic Redlining Grade")

holc_map

#Return to normal analysis

boston_holc_zip <- boston_holc_tract_zip %>%
  group_by(ZCTA) %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))

boston_covid_holc <- merge(boston_covid_df, boston_holc_zip)

summary(is.na(boston_covid_holc))

colnames(boston_covid_holc)[2] <- "YEAR"

boston_redlining_df <- merge(boston_covid_holc, df_demo, by = c("ZCTA", "YEAR"))


```

#Reorganizing time

```{r}

boston_redlining_df <- filter(boston_redlining_df, !(YEAR == 2020 & month == 1))

boston_redlining_df <- boston_redlining_df %>% mutate(
  cumulative_months = case_when(
    YEAR == 2020 ~ month,
    YEAR == 2021 ~ month + 12,
    YEAR == 2022 ~ month + 24  )
)

boston_redlining_df$time_0 <- as.numeric(boston_redlining_df$cumulative_months) - 2

```


#Demographic percentages

```{r}
colnames(boston_redlining_df)
boston_redlining_df <- boston_redlining_df %>%
   mutate_at(vars(21:23, 26:32) , funs(P = ./boston_redlining_df$zip_pop * 100))

boston_redlining_df$no_bach_P <- 100 - boston_redlining_df$COL_P
boston_redlining_df$non_white_pop_P <- 100 - boston_redlining_df$NHWHT_P
```

#Creating incidence rate

```{r}

summary(boston_redlining_df$zip_pop) #mean 25000

boston_redlining_df$incidence_rate_25k <- (boston_redlining_df$zip_count_est / boston_redlining_df$zip_pop) * 25000

boston_redlining_df$incidence_rate_10k <- (boston_redlining_df$zip_count_est / boston_redlining_df$zip_pop) * 10000

summary(boston_redlining_df$incidence_rate_10k)

boston_redlining_df$stnd_median_hh_value <- standardise(boston_redlining_df$MHMVAL)

```

#Cases and Death dfs

```{r}

boston_cases_df <- filter(boston_redlining_df, indicator == "New Cases")

boston_deaths_df <- filter(boston_redlining_df, indicator == "Deaths")

boston_glm_df <- filter(boston_cases_df, time_0 != 0)

boston_glm_na_df <- filter(boston_glm_df, ZCTA != "02199") # No one lives in this ZIP code so there were no COVID cases

```


#testing relationship between HOLC Grade and Median Household Value today

```{r}
cor(boston_glm_na_df$HRI2020, boston_glm_na_df$stnd_median_hh_value) #0.190

summary(lm(stnd_median_hh_value ~ HRI2020, boston_glm_na_df)) #for every unit increase in HRI score, median household value is expected to increase by 0.379 SD

holc_means <- boston_glm_na_df %>%
  group_by(INTERVAL2020) %>%
  summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)))

ggplot(holc_means, aes(INTERVAL2020, stnd_median_hh_value)) +
  geom_point() + 
  geom_smooth(method = lm,
              se = FALSE)


unique(boston_glm_na_df$ZCTA)
```


##Main analysis dataset

```{r}
#Cases incidence rate variation by HRI

ggplot(data = boston_glm_na_df, aes(factor(x = time_0), y = log(incidence_rate_10k), group = ZCTA, color = factor(as.integer(INTERVAL2020)))) +
  geom_line() +
  ylab("incidence rate\n") + 
  xlab("\nHistorical redlining indicator") + # space before the title
  theme_bw()


```


```{r}

colnames(boston_glm_na_df)

tbl1 <- boston_glm_na_df %>% dplyr::select(c("ZCTA", "YEAR", "incidence_rate_10k", "zip_pop", "HRI2020", "FB_P", "no_bach_P", "MHMVAL", "non_white_pop_P", "A75UP_P", "NHWHT_P", "NHBLK_P", "ASIAN_P", "HISP_P" ))
tbl1 <- tbl1 %>%
  group_by(ZCTA) %>%
  summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)))

Desc(tbl1)

table(boston_glm_na_df$ZCTA)

```

#non-hierarchical

```{r}
colnames(boston_glm_na_df)

glm1 <- glm(log(incidence_rate_10k) ~ time_0 + A75UP_P, boston_glm_na_df, family = gaussian)
glm1 %>% tbl_regression(exponentiate = TRUE)
AIC(glm1) #2516
qqnorm(residuals(glm1)) #best qqplot
qqline(residuals(glm1))

glm2 <- glm(log(incidence_rate_10k) ~ HRI2020 + time_0 + A75UP_P, boston_glm_na_df, family = gaussian)
glm2 %>% tbl_regression(exponentiate = TRUE)
AIC(glm2) #2517

glm3 <- glm(log(incidence_rate_10k) ~ HRI2020 + stnd_median_hh_value + time_0 + A75UP_P, boston_glm_na_df, family = gaussian)
glm3 %>% tbl_regression(exponentiate = TRUE)
AIC(glm3) #2518

#Main model

glm4 <- glm(log(incidence_rate_10k) ~ HRI2020 + FB_P + stnd_median_hh_value + non_white_pop_P + OWN_P + time_0 + A75UP_P, boston_glm_na_df, family = gaussian)
glm4 %>% tbl_regression(exponentiate = TRUE)
AIC(glm4) #2494 lower than undadjusted
qqnorm(residuals(glm4)) #best qqplot
qqline(residuals(glm4))
plot(glm4)

#Expanded non-white category 
glm5 <- glm(log(incidence_rate_10k) ~ HRI2020 + FB_P + stnd_median_hh_value + NHBLK_P + HISP_P + ASIAN_P + OWN_P + time_0 + A75UP_P, boston_glm_na_df, family = gaussian)
glm5 %>% tbl_regression(exponentiate = TRUE)
AIC(glm5) #2498.151 higher than composite variable
qqnorm(residuals(glm5)) #best qqplot
qqline(residuals(glm5))
plot(glm5)


```




